### ISSUE TITLE
[fslibre] Comments ASCII encoding

### ISSUE THREAD

**Issue by capsuleman** [glucometers-tech/glucometerutils#103]
Hi,
With the FreeStyle libre software, I added some comments in French, including "Modérée". After I added it, dumping the data from my device was blocked by invalid checksum.
I removed it after with the software but the checksum is still invalid.
Using this command: `glucometer --driver fslibre --vlog=4 --device /dev/hidraw4 dump`, I get these lines in log:
```
DEBUG:root:Received message: type 60 content 313636312c322c322c32382c32312c392c33382c34392c312c322c302c302c3132362c312c342c302c302c302c302c302c302c302c332c302c302c302c30
DEBUG:root:Read packet: b'`8,0,0,"Intense","Mod\xc3\xa9r\xc3","Fin de sport","Alcool","",""\r\nl",""\r'
DEBUG:root:Received message: type 60 content 2c302c302c22496e74656e7365222c224d6f64c3a972c3222c2246696e2064652073706f7274222c22416c636f6f6c222c22222c22220d0a
```
and
```
1661,2,2,28,21,9,38,49,1,2,0,0,126,1,4,0,0,0,0,0,0,0,3,0,0,0,0,0,0,"Intense","Mod��r�","Fin de sport","Alcool","",""
```
and outputs this in stderr:
```
ChecksumError: Invalid checksum, expected 1697137, calculated 1893177
```

As temporary fix, I ignored the related checksum.

This issue seems to be related to the [non-ASCII patient name one](https://github.com/glucometers-tech/glucometerutils/issues/60).

Is there a way to fix it?
Best regards

**Comment by Flameeyes** [comment]
Hello — yeah that does seem like there's something going wrong with the encoded message, and I'll be digging into this right now.

I guess I need to try if my app allows me to add these comments (I guess in France there's still the "full" version available for download, not just the LibreLink driver? That should be easy then.) and see if I can read it back.

Interesting point here: `Modérée` is 7 characters long, which would be 9 bytes long in UTF-8 encoding. The truncation here is not just one byte, but two (the last `e` is missing). So if the data is reported correctly with the binary protocol, but incorrectly with the data export, the firmware might actually have a bug in handling UTF-8. 

(Unrelated, but if your device happens to be a mg/dL device, have a look at https://github.com/glucometers-tech/glucometer-protocols/issues/10 — I'm still looking to confirm the correct unit of measure.)

**Comment by Flameeyes** [comment]
Okay this is fun, the bug is in the _host_ software, not the firmware. In the chatter, when I try to set two custom comments, one being `Modérée` and the other being `òòòòò`, I see this:

```
[ 0a] H>>D 00000000: 02 0A 6B 29 40 8F 81 82  52 07 4D 6F 64 C3 A9 72  ..k)@...R.Mod..r
[ 0a] H>>D 00000010: C3 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
[ 0a] H>>D 00000020: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
[ 0a] H>>D 00000030: 00 00 00 00 C3 B2 C3 B2  C3 00 00 00 00 00        .............. 
```

The important part is that both strings are cut short, and if I read them back with the software, the `é` is replaced with the unknown character both times (surprisingly so, as the first one appears to be fine), and if I try to set this with just `òòòò` I get a further truncated string:

```
[ 0a] H>>D 00000000: 02 0A D4 86 E1 E7 81 82  52 07 4D 6F 64 C3 A9 72  ........R.Mod..r
[ 0a] H>>D 00000010: C3 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
[ 0a] H>>D 00000020: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
[ 0a] H>>D 00000030: 00 00 00 00 C3 B2 C3 B2  00 00 00 00 00 00        .............. 
```

So yeah, congrats to us we found a bug in the original software 😄

I'm looking to fix this now.

**Comment by Flameeyes** [comment]
Please confirm this works when installing `pip install -U "git+https://github.com/glucometers-tech/freestyle-hid`, and if not, re-open this change.

**Comment by capsuleman** [comment]
Thanks for your response @Flameeyes!
I tried your version using `pip3 install -U "git+https://github.com/Flameeyes/freestyle-hid"`, and its working! :tada: 
Thank you very much!

> Interesting point here: `Modérée` is 7 characters long, which would be 9 bytes long in UTF-8 encoding. The truncation here is not just one byte, but two (the last `e` is missing). So if the data is reported correctly with the binary protocol, but incorrectly with the data export, the firmware might actually have a bug in handling UTF-8.

Yes, I noticed that and now it is fixed for all custom comments, including ones special characters


> (Unrelated, but if your device happens to be a mg/dL device, have a look at [glucometers-tech/glucometer-protocols#10](https://github.com/glucometers-tech/glucometer-protocols/issues/10) — I'm still looking to confirm the correct unit of measure.)

It is the correct unit of measure for my device. In France we are mostly using mg/dL or g/L.



> So yeah, congrats to us we found a bug in the original software smile

Well done! :smile:

**Comment by Flameeyes** [comment]
> Thanks for your response @Flameeyes!
> I tried your version using `pip3 install -U "git+https://github.com/Flameeyes/freestyle-hid"`, and its working! 
> Thank you very much!

Thank you for reporting this! I'll make a new release of freestyle-hid tomorrow and will update glucometerutils to require it for the fslibre driver.

> > (Unrelated, but if your device happens to be a mg/dL device, have a look at [glucometers-tech/glucometer-protocols#10](https://github.com/glucometers-tech/glucometer-protocols/issues/10) — I'm still looking to confirm the correct unit of measure.)
> 
> It is the correct unit of measure for my device. In France we are mostly using mg/dL or g/L.

Great! Could you please try installing `pip3 install -U "git+https://github.com/Flameeyes/freestyle-hid[tools]"`, running `freestyle-hid-console -p 13904` (which opens a console to the Libre device) and tell me the output of running `$uom?` as the command prompt?

If it's anything beside 0 we have a way to autodetect the right unit of measure. Otherwise we're back to square one unfortunately. (I only have access to mmol/l devices here.)

Thank you!
