### ISSUE TITLE
Failed to install latest version of glucometerutils

### ISSUE THREAD

**Issue by richardquint** [glucometers-tech/glucometerutils#112]
I have failed to install the latest version of glucometerutils (as of 2021 Sept 23).
I started by downloading the zip file from

https://github.com/glucometers-tech/glucometerutils

but when after opening a terminal in the extracted folder I tried to install the following occurred

> 
> rquint@Polly:~/Desktop/glucometerutils-main$ sudo python setup.py install
> [sudo] password for rquint:
> Traceback (most recent call last):
>   File "/home/rquint/Desktop/glucometerutils-main/setup.py", line 44, in <module>
>     setup(
>   File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
>     return distutils.core.setup(**attrs)
>   File "/usr/lib/python3.9/distutils/core.py", line 108, in setup
>     _setup_distribution = dist = klass(attrs)
>   File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 432, in __init__
>     _Distribution.__init__(self, {
>   File "/usr/lib/python3.9/distutils/dist.py", line 292, in __init__
>     self.finalize_options()
>   File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 708, in finalize_options
>     ep(self)
>   File "/usr/local/lib/python3.9/dist-packages/setuptools_scm/integration.py", line 94, in infer_version
>     dist.metadata.version = _get_version(config)
>   File "/usr/local/lib/python3.9/dist-packages/setuptools_scm/__init__.py", line 177, in _get_version
>     parsed_version = _do_parse(config)
>   File "/usr/local/lib/python3.9/dist-packages/setuptools_scm/__init__.py", line 135, in _do_parse
>     raise LookupError(
> LookupError: setuptools-scm was unable to detect version for '/home/rquint/Desktop/glucometerutils-main'.
> 
> Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
> 
> For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj

I assume this means the zipped file doesn't contain the necessary metadata, but how do I remedy that.  I have installed older versions of glucometerutils without any problem, but thought I'd try the latest on a fresh install of Ubuntu 21.04.

**Comment by Flameeyes** [comment]
Please follow the instructions at https://github.com/glucometers-tech/glucometerutils#example-usage to install the project.

The zip file you downloaded is the source itself, but while it can be installed, it's not done through the `setup.py` file.
