### ISSUE TITLE
Message to connect

### ISSUE THREAD

**Issue by bassignana** [glucometers-tech/glucometerutils#121]
Hi,

my name is Tommaso Bassignana and, like you, I am interested in the healthcare space, specifically in developing solutions for diabetic people. I am currently in the process of developing some solutions, and I have a vision of founding a company to help improve the lives of those living with diabetes.

If you are interested, please feel free to reach out to me, so we can discuss potential collaborations further.

Thank you for your time and consideration,

Tommaso Bassignana

Telegram: @T_bax

LI: [https://www.linkedin.com/in/tommaso-bassignana/](https://www.linkedin.com/in/tommaso-bassignana/)

**Comment by Flameeyes** [comment]
This is both disrespectful and useless.

I have already written my response to this kind of behaviour.
 https://flameeyes.blog/2016/04/02/last-words-on-diabetes-and-software/
