### ISSUE TITLE
Libre2/3 support

### ISSUE THREAD

**Issue by Coreforge** [glucometers-tech/glucometerutils#123]
Since the problem with the newer libre readers is the encryption, a workaround to that would be to let LibreReaderInterface.dll set up the communication and handle the encryption, then hook the first function call that sends a command to the reader and send different commands instead to dump the data. I have some working code for this that dumps the response for history, arresult and patch, but more commands would be possible too. One limitation currently is that all commands have to be sent at once, but it should still be possible to get all the needed data. 

Is this something that would be useful to add, or would it be better to have it as a separate program?
I also only have it working on windows so far, it launches with wine, but doesn't detect the reader.

**Comment by Flameeyes** [comment]
Sorry but no this project should only have cleanroom code.
