### ISSUE TITLE
Failing to install on Xubuntu 18.04

### ISSUE THREAD

**Issue by bonelifer** [glucometers-tech/glucometerutils#89]
ERROR: Package u'glucometerutils' requires a different Python: 2.7.17 not in '~=3.7'

**Comment by Flameeyes** [comment]
You need to install using python3. Python 2 is not supported.

**Comment by bonelifer** [comment]
I have 3.7 and 3.6.9

**Comment by Flameeyes** [comment]
But you're running it with 2.7 right now.

Try `python3 -m pip install .`

**Comment by bonelifer** [comment]
had to uninstall and reinstall python3 and force update pip3. also had to install libusb-1.0.0-dev, then "sudo apt-get install python3.7-dev".  then "virtualenv -p python3.7 env" Then it compiled finally.

**Comment by bonelifer** [comment]
Thanks for this great program. Unforunately Abbotts software doesn't install with WINE.
